[project]
name = "overgrazed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markdown>=3.9",
    "mdx-wikilink-plus>=1.4.1",
    "pygments>=2.19.2",
    "watchdog>=6.0.0",
]
